// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkysnxsythjmgqgeardx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJreXNueHN5dGhqbWdxZ2VhcmR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMTYwMjYsImV4cCI6MjA2ODg5MjAyNn0.9nUd8addRHm-39UXDJYUZTWR0ASi0yU3Ew_SkkPkR1c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});